name: Update Profile README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Generate README
        run: go run main.go
      - name: Push changes
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git diff --quiet README.md || (git add README.md && git commit -m 'chore: updated readme' && git push)
