name: Update Profile README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.3
      - name: Run Update
        run: |
          poetry install
